In [1]:
import numpy as np

In [4]:
n1 = np.random.random((3,3,3))

In [5]:
print(n1)

[[[5.88156847e-01 8.29396562e-01 2.44217978e-01]
  [4.10266228e-01 9.67208939e-01 5.55922757e-01]
  [7.09538613e-02 6.88888318e-01 9.80052998e-01]]

 [[7.62816988e-01 2.40255192e-04 9.57167210e-01]
  [1.08356765e-01 3.05571333e-01 7.83166367e-01]
  [9.13171426e-01 7.32827442e-01 8.70959699e-01]]

 [[6.16249728e-01 4.59494629e-01 1.84257140e-01]
  [6.09537806e-01 3.21038803e-01 3.82033650e-01]
  [5.80692364e-01 4.48080216e-01 2.82312425e-01]]]
